/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter
  {
    export interface __routes<T extends string | object = string>
    {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/app${'/(tabs)'}/cart` | `/../components/app/cart`; params?: Router.UnknownInputParams; } | { pathname: `/../components/app${'/(tabs)'}/index` | `/../components/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/app${'/(tabs)'}/profile` | `/../components/app/profile`; params?: Router.UnknownInputParams; } | { pathname: `/../components/app/product/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../components/components/ProductCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/product/[id]`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ProductCard`; params?: Router.UnknownInputParams; } | { pathname: `/../context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/app${'/(tabs)'}/cart` | `/../components/app/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/app${'/(tabs)'}/index` | `/../components/app/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/app${'/(tabs)'}/profile` | `/../components/app/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/app/product/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/components/ProductCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/context/CartContext`; params?: Router.UnknownOutputParams; } | { pathname: `/product/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ProductCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../context/CartContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../components/app${'/(tabs)'}/cart${`?${string}` | `#${string}` | ''}` | `/../components/app/cart${`?${string}` | `#${string}` | ''}` | `/../components/app${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/../components/app/index${`?${string}` | `#${string}` | ''}` | `/../components/app${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/../components/app/profile${`?${string}` | `#${string}` | ''}` | `/../components/app/product/[id]${`?${string}` | `#${string}` | ''}` | `/../components/components/ProductCard${`?${string}` | `#${string}` | ''}` | `/../components/context/CartContext${`?${string}` | `#${string}` | ''}` | `/product/[id]${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cart${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/../components/ProductCard${`?${string}` | `#${string}` | ''}` | `/../context/CartContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/app${'/(tabs)'}/cart` | `/../components/app/cart`; params?: Router.UnknownInputParams; } | { pathname: `/../components/app${'/(tabs)'}/index` | `/../components/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/app${'/(tabs)'}/profile` | `/../components/app/profile`; params?: Router.UnknownInputParams; } | { pathname: `/../components/app/product/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../components/components/ProductCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/product/[id]`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ProductCard`; params?: Router.UnknownInputParams; } | { pathname: `/../context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
